# Makefile for MHI driver
#obj-y += mhi_main.o
#obj-y += mhi_iface.o
#obj-y += mhi_init.o
#obj-y += mhi_isr.o
#obj-y += mhi_mmio_ops.o
#obj-y += mhi_ring_ops.o
#obj-y += mhi_states.o
#obj-y += mhi_sys.o
#obj-y += mhi_bhi.o
#obj-y += mhi_pm.o
#obj-y += mhi_ssr.o
obj-m := mhi.o
mhi-objs := mhi_main.o mhi_iface.o mhi_init.o mhi_isr.o mhi_mmio_ops.o mhi_ring_ops.o mhi_states.o mhi_sys.o mhi_uci.o msm_rmnet_mhi.o mhi_bhi.o mhi_pm.o mhi_ssr.o
